### ISSUE TITLE
light-theme support

### ISSUE THREAD

**Issue by chentao7v** [Zabriskije/Typora-GitHub-Themes#1]
The default Github theme of Typora was not like the official Github markdown style, such as h1 title

**Comment by Zabriskije** [comment]
Thanks for the issue. I'm not sure I'm following you: are you referring to the default GitHub theme that comes with Typora?
Because I have no authority over default themes, you should ask in the [theme.typora.io repo](https://github.com/typora/theme.typora.io) for that.

If that's not the case, can you provide me a screenshot and OS info?

**Comment by chentao7v** [comment]
![Typora Default Github Theme](https://github.com/Zabriskije/Typora-GitHub-Themes/assets/17487668/123d969b-9a94-42b8-ae15-c63a1ba6c755)
![Github Dark Theme](https://github.com/Zabriskije/Typora-GitHub-Themes/assets/17487668/3d4e418a-4200-450b-99c1-1992a7d579f9)
![Official Github README Theme](https://github.com/Zabriskije/Typora-GitHub-Themes/assets/17487668/52207b95-df7f-4ccd-9dde-d3f9c6d0d438)

**Comment by chentao7v** [comment]
Those pictures are `Typora Default Github Theme`,`Github Dark High Light Theme by you` and `Official Github README Theme`, you can see the margins of the divider line are not the same.

**Comment by Zabriskije** [comment]
![github](https://github.com/Zabriskije/Typora-GitHub-Themes/assets/101254295/2d3d4e5a-5543-4f10-a6cd-0dd9d6be0dbc)

# Google

## Google

&nbsp;

Seems pretty spot on

**Comment by chentao7v** [comment]
the default GitHub theme?

**Comment by Zabriskije** [comment]
> the default GitHub theme?

If you were asking which theme is the image, I just cropped the second one you shared

**Comment by chentao7v** [comment]
What I mean is that the official Typora default theme is still different from the GitHub README theme, and the theme you made is similar to the official GitHub theme, so I'd like to ask you to provide a light version 😂

**Comment by Zabriskije** [comment]
> What I mean is that the official Typora default theme is still different from the GitHub README theme, and the theme you made is similar to the official GitHub theme, so I'd like to ask you to provide a light version 😂

Sorry for the misunderstanding. Unfortunately, I'm not interested in making a light version since I don't use the light themes myself.

**Comment by chentao7v** [comment]
Okay, thanks for the reply.

**Comment by chentao7v** [comment]
> > What I mean is that the official Typora default theme is still different from the GitHub README theme, and the theme you made is similar to the official GitHub theme, so I'd like to ask you to provide a light version 😂
> 
> Sorry for the misunderstanding. Unfortunately, I'm not interested in making a light version since I don't use the light themes myself.

Okay, thanks for the reply.
